# Generated by Django 3.0.2 on 2020-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0002_auto_20200115_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
