# Generated by Django 3.0.2 on 2020-01-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0003_auto_20200115_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
