# Generated by Django 3.0.2 on 2020-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField(auto_now=True)),
                ('tipo', models.BooleanField()),
            ],
        ),
    ]
